### ISSUE TITLE
Problem with scripts in OSX

### ISSUE THREAD

**Issue by Troppik** [upjs-jf/mdh#10]
Hi all,

I have platform OS X El Capitan (Version 10.11.6) and after run command 

`$ scripts/make.sh`

it failed.

<img width="605" alt="screen shot 2017-04-12 at 11 30 52" src="https://cloud.githubusercontent.com/assets/26110448/24951378/77efe482-1f74-11e7-8202-809b2fdf761c.png">

Thank you in advance.

**Comment by mvala** [comment]
Can you test ```libMdh.dylib``` instead of ```libMdh.so```?
```
gSystem->Load("libMdh.dylib")
```

**Comment by ltropp** [comment]
Hi @mvala ,
i tested it and obtained 

<img width="1275" alt="screen shot 2017-04-28 at 12 10 53" src="https://cloud.githubusercontent.com/assets/27418831/25524698/f17d3fd6-2c0b-11e7-953e-79e6765f7363.png">

and I still don't receive a confirmation mail for permission "git push"

**Comment by mvala** [comment]
tak ty si @ltropp or @Troppik

**Comment by Troppik** [comment]
Sorry my mistake, I have 2 accounts and I did not notice switch between them. I am Troppik.
I ran 
`$ ./make.sh clean install`
and now it works I think 

<img width="802" alt="screen shot 2017-04-28 at 12 57 00" src="https://cloud.githubusercontent.com/assets/26110448/25526389/9f1446e2-2c13-11e7-9fb2-b75f84dcbb0f.png">

<img width="310" alt="screen shot 2017-04-28 at 13 06 30" src="https://cloud.githubusercontent.com/assets/26110448/25526397/a4cb60c0-2c13-11e7-985f-d6fde03fecdb.png">

**Comment by mvala** [comment]
Super

**Comment by mvala** [comment]
I just sent you another invitation
