### ISSUE TITLE
exam lhusova

### ISSUE THREAD

**Issue by lhusova** [upjs-jf/mdh#18]
Where should I define the data members like TFile or THnSparse?

**Comment by mvala** [comment]
Where is this error?

**Comment by lhusova** [comment]
I receive the error by compiling. I have wrong defined data members fFileName and fHistName.
error: cannot initialize a member subobject of type 'TString *' with an lvalue of type 'const char *'
    : MdhTask(name, title), fFileName(file), fHistName(histname)

**Comment by mvala** [comment]
i see
```
/home/mvala/MVALA/git/github/upjs-jf/mdh/Mdh/MdhTaskInput.h:14:72: error: member reference base type 'const char *' is not a structure or union
  virtual void SetFileName(const char * filename) {fFileName = filename.Data();}
                                                               ~~~~~~~~^~~~~
/home/mvala/MVALA/git/github/upjs-jf/mdh/Mdh/MdhTaskInput.h:15:72: error: member reference base type 'const char *' is not a structure or union
  virtual void SetHistName(const char * histname) {fFileName = histname.Data();}
                                                               ~~~~~~~~^~~~~
```

**Comment by mvala** [comment]
filename is const char so it doesn't have Data function to fix it
```
 virtual void SetFileName(const char * filename) {fFileName = filename;}
```

**Comment by mvala** [comment]
And also TString should not be pointer

**Comment by lhusova** [comment]
I fixed the erros but how can I get the histogram from the parent task? I receive an error:
`/Users/lhusova/Documents/mdh/Mdh/MdhTaskBin.cxx:15:5: error: use of undeclared identifier 'fHistSparse'
    fHistSparse->GetAxis(fCutAxis)->SetRangeUser(fCutMin,fCutMax);`

**Comment by mvala** [comment]
I just pushed you fix. Please do ```git pull``` and have a look at differences

**Comment by lhusova** [comment]
Thank you, I can build the project now, but when I run the macro exam_task.C there is one more error: `Error: Symbol MdhTaskInput is not defined in current scope  exam_task.C:8:` Shouldn't I install the new libraries or something like that?

**Comment by mvala** [comment]
are you doing
```
source scripts/env.sh
```
?

**Comment by lhusova** [comment]
Yes I have already done it, but the error is still there

**Comment by mvala** [comment]
I can reproduce it on root5 (from aliroot). This is output i was expecting from you to see error
```
12:56 $ root macros/exam_task.C 
root [0] 
Processing macros/exam_task.C...
Error: Symbol MdhTaskInput is not defined in current scope  macros/exam_task.C:6:
Error: Symbol MdhTaskInput is not defined in current scope  macros/exam_task.C:6:
Error: type MdhTaskInput not defined FILE:/home/mvala/MVALA/git/github/upjs-jf/mdh/./macros/exam_task.C LINE:6
Warning: Automatic variable MdhTaskInput*tInput is allocated macros/exam_task.C:6:
Error: Undeclared variable MdhTaskInput*tInput macros/exam_task.C:6:
*** Interpreter error recovered ***
root [1] .q
```

**Comment by lhusova** [comment]
That is excatly the error I see.

**Comment by mvala** [comment]
i just push the fix in macro. But what i see you on osx you will have to set LD_LIBRARY_PATH by hand. You will not be able to user ```scripts/env.sh```. I don't have time to fix OSX specific things. So try

**Comment by lhusova** [comment]
The Problem is, that I don't have the lybrary libMdh.so in the /Users/lhusova/Documents/mdh/lib only libMdh.dylib . how can I make the library .so?

**Comment by mvala** [comment]
make link
```
ln -s libMdh.dylib libMdh.so
```

**Comment by lhusova** [comment]
Thank you, everything works now

**Comment by mvala** [comment]
So please add all Bin tasks like it is number of bins in sparse. SO we will see projections in ```TBrowser```

**Comment by lhusova** [comment]
I actually don't understand, what you mean. And I have one more question: how can I create an outputfile. Would be possible to do it this way:
`TList* list=tBin1->GetOutput();
TH1D *h=list->At(1);`
and to write this histogram to an output file? Or is there another way, how to do this<

**Comment by mvala** [comment]
You can save most top task to file and it should be ok.
```
TFile *f = TFile::Open("out.root","RECREATE");
tInput->Write();
f->Close();
```

**Comment by lhusova** [comment]
And what should I with the bin tasks and  the number of bins in sparse?

**Comment by mvala** [comment]
Nothing. They will be saved automatically since they are sub-task of tInput

**Comment by lhusova** [comment]
But two comments ago, you wrote: So please add all Bin tasks like it is number of bins in sparse.
so my question is, what should I do with the numbers. I didn't understand it

**Comment by mvala** [comment]
That you will do for cycle to add all bins
```
for (int i=1;i<20;i++) {
  MdhTaskBin *bin = new MdhTaskBin("exam_bin2", "", 0, 1, i, i+1);
  tInput->AddTask(bin);
}
```

**Comment by lhusova** [comment]
ok, I've already pushed it

**Comment by mvala** [comment]
I fixed some small things in exam_task.C macro. So please have a look. Note that in root you can use ```TString::Format("sdsdgs %d",integer).Data()``` and it will return formated string

**Comment by lhusova** [comment]
Thanks for the changes, should I do something more, or is my exam done now?

**Comment by mvala** [comment]
Done. I will close issue when i will give you A
