### ISSUE TITLE
Off topic questions

### ISSUE THREAD

**Issue by Troppik** [upjs-jf/mdh#2]
1. If I remembered right, Martin mentioned that he will show us how to use root/aliroot without instalation on particular ntb. Do you have any procedure or we will consult it next week ?

2. Does anybody has an experiences with PyRoot ? I want to write code in python by using root's libraries but it doesn't work for me.

3. During my analysis I met with some little troubles and missing informations about functions which I am using. For example, does anybody know meaning of integer value of Event selection code ? (it gets values like 200,203,204,0) In my analysis I need zero value but I really don't know why, meaning of zero value.

4. I am enclosing pdf file where you can clearly see the different between projection and profile :)
In this issue I wanted just try how it works, but your useful answers are welcome :)

[2Dhisto_and_proj_and_prof.pdf](https://github.com/upjs-jf/mdh/files/827591/2Dhisto_and_proj_and_prof.pdf)

**Comment by mvala** [comment]
@Troppik 
1. Yes i can show it next week.
2. I can show you how. (Please write new issue about python and i will give you example end procedure)
3. Now, i cannot answer. Please report it in alice project (i will create it)
4. Thanks
