### ISSUE TITLE
Python + Root = PyRoot

### ISSUE THREAD

**Issue by Troppik** [upjs-jf/mdh#3]
This issue will be dedicated to using,installing and troubles with PyRoot. 
Do I have to need install some additionally libraries or set up paths for reading existing libraries ? 
Because I tried examples on 
https://root.cern.ch/root/htmldoc/guides/users-guide/PythonRuby.html 
but it doesn't work. 
Maybe this will be useful for all of you and once everyone tried python because in my opinion it is stupidity-protected language :D :)  (I know that @fisopkov is already using it.)
@mvala promise that he will show us working examples, thank you !

**Comment by mvala** [comment]
Fixed
